import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight:['100','200','300','400','600','800'],
  subsets:['latin']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"

    >
      <body className={`${poppins.className} antialiased`}>
        <header className="w-full">
         <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2">
           <Navbar></Navbar>

         </div>
        </header>
        
        <main className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2">
          {children}
        </main>

       <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2">
         <footer className="py-2 md:w-11/12 mx-auto">
          <Footer></Footer>
        </footer>
       </div>
        </body>
    </html>
  );
}
